version: '3.8'

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: skillbox
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongodb-data:/data/db

  catalog-service:
    container_name: catalog-service
    build:
      context: ./catalog-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
      - "5007:5007"
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_MAIN_ALLOW_BEAN_DEFINITION_OVERRIDING: "true"
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/skillbox
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres
      - mongodb

  payment-service:
    container_name: payment-service
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "5008:5008"
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_MAIN_ALLOW_BEAN_DEFINITION_OVERRIDING: "true"
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/skillbox
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      ENV_CATALOG_SERVICE_URL: http://catalog-service:8082
    depends_on:
      - postgres
      - mongodb

volumes:
  postgres-data:
  mongodb-data:
