version: '3.8'

services:
  postgres:
    container_name: postgres_skillbox
    image: postgres:17
    environment:
      POSTGRES_DB: skillbox
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongodb:
    container_name: mongo_skillbox
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongodb-data:/data/db


  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "15672:15672"  # Web UI
      - "5672:5672"    # AMQP protocol
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit


  catalog-service:
    container_name: catalog-service
    build:
      context: ./catalog-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
      - "5007:5007"
    environment:
      SPRING_DATA_MONGODB_HOST: mongo_skillbox
#      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_MAIN_ALLOW_BEAN_DEFINITION_OVERRIDING: "true"
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_skillbox:5432/skillbox
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
      ENV_PAYMENT_SERVICE_URL: "http://payment-service:8080"
      ENV_RABBIT_MQ_HOST: rabbitmq
    depends_on:
      - postgres
      - mongodb
      - rabbitmq


  payment-service:
    container_name: payment-service
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "5008:5008"
    environment:
      SPRING_DATA_MONGODB_HOST: mongo_skillbox
#      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_MAIN_ALLOW_BEAN_DEFINITION_OVERRIDING: "true"
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_skillbox:5432/skillbox
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
      ENV_CATALOG_SERVICE_URL: http://catalog-service:8082
      ENV_RABBIT_MQ_HOST: rabbitmq
    depends_on:
      - postgres
      - mongodb
      - rabbitmq

  notification-service:
    container_name: notification-service
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    ports:
      - "9094:9094"
      - "5009:5009"
    environment:
      ENV_RABBIT_MQ_HOST: rabbitmq
  
  
  
volumes:
  postgres-data:
  mongodb-data:
