version: '3.8'

services:
  postgres:
    container_name: postgres_skillbox
    image: postgres:17
    environment:
      POSTGRES_DB: skillbox
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongodb:
    container_name: mongo_skillbox
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongodb-data:/data/db


  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "15672:15672"  # Web UI
      - "5672:5672"    # AMQP protocol
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit

volumes:
  postgres-data:
  mongodb-data:
